import logoSlack from "./assets/logoSlack.png";
import logoMeet from "./assets/logoMeet.png";
import logoGithub from "./assets/LogoGithub.png";
import logoDrive from "./assets/logoDrive.png";
import logoFigma from "./assets/logoFigma.png";
import logoTrello from "./assets/logoTrello.png";
import logoWild from "./assets/logoWild.png";
import logoDiscord from "./assets/discord.png";

import alex from "./assets/alex.jpg";
import amaury from "./assets/amaury.jpg";
import bryan from "./assets/bryan.jpg";
import cathy from "./assets/cathy.jpg";
import delphine from "./assets/delphine.jpg";
import fabien from "./assets/fabien.jpg";
import julien from "./assets/julien.jpg";
import laetitia from "./assets/laetitia.jpg";
import laurence from "./assets/laurence.jpg";
import nicolas_r from "./assets/nicolas_r.jpg";
import nicolas_w from "./assets/nicolas_w.jpg";
import nils from "./assets/nils.jpg";
import thomas_d from "./assets/thomas_d.jpg";
import thomas_v from "./assets/thomas_v.jpg";
import waheb from "./assets/waheb.png";
import wilhem from "./assets/wilhem.jpg";

const student = [
  {
    Name: "Nicolas W",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "0618109927",
    github: "https://github.com/nimser",
    picture: nicolas_w,
    linkedin: "",
  },
  {
    Name: "Cathy",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "0618109927",
    github: "https://github.com/121019",
    picture: cathy,
    linkedin: "",
  },
  {
    Name: "Alex",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "0618109927",
    github: "https://github.com/alexdubrulle",
    picture: alex,
    linkedin: "",
  },
  {
    Name: "Waheb",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "0618109927",
    github: "https://github.com/Waheb26",
    picture: waheb,
    linkedin: "https://www.linkedin.com/in/waheb-cheraifia-58a314269/",
  },
  {
    Name: "Nicolas R",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "+33686537628",
    github: "https://github.com/TaupeHumide",
    picture: nicolas_r,
    linkedin: "",
  },
  {
    Name: "Nils",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "0618109927",
    github: "https://github.com/Stagy73",
    picture: nils,
    linkedin: "https://www.linkedin.com/in/nils-mehlhorn-51152823b",
  },
  {
    Name: "Thomas D",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "0618109927",
    github: "https://github.com/ThomasD26",
    picture: thomas_d,
    linkedin: "",
  },
  {
    Name: "Fabien",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "0618109927",
    github: "https://github.com/fabienchbd",
    picture: fabien,
    linkedin: "https://www.linkedin.com/in/fabien-c-012658b3",
  },
  {
    Name: "Thomas V",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "0618109927",
    github: "https://github.com/Thomas-VWD",
    picture: thomas_v,
    linkedin: "https://www.linkedin.com/in/thomas-verwaerde-758a60131/",
  },
  {
    Name: "Laetitia",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "0618109927",
    github: "https://github.com/Laetitia-gb",
    picture: laetitia,
    linkedin: "",
  },
  {
    Name: "Amaury",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "0618109927",
    github: "https://github.com/AmauryClt",
    picture: amaury,
    linkedin: "https://www.linkedin.com/in/amaury-c-483030251",
  },
  {
    Name: "Julien",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "0618109927",
    github: "https://github.com/julien-lad",
    picture: julien,
    linkedin: "https://www.linkedin.com/in/jl26",
  },
  {
    Name: "Delphine",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "0618109927",
    github: "https://github.com/Delphine2669",
    picture: delphine,
    linkedin: "https://www.linkedin.com/in/delphine-thevenet-66520a130/",
  },
  {
    Name: "Wilhem",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "0681019972",
    github: "https://github.com/Wilhem-H",
    picture: wilhem,
    linkedin: "https://www.linkedin.com/in/wilhem-hafsa/",
  },
  {
    Name: "Bryan",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "0618109927",
    github: "https://Plus-parmis-nous",
    picture: bryan,
    linkedin: "",
  },
  {
    Name: "Laurence",
    mail: "wilhem.hafsa@outlook.fr",
    phone: "0618109927",
    github: "https://Plus-parmis-nous",
    picture: laurence,
    linkedin: "",
  },
];

const links = [
  {
    name: "Silent Teacher ",
    link: "https://silentteacher.toxicode.fr/",
    type: "Pratique / Exercices",
    category: "Algo",
    desc: "Interface web ludique pour vous aider à comprendre quelques bases JS/Algo.",
  },
  {
    name: "Scrimba",
    link: "https://scrimba.com/learn/learnreact/",
    type: "Cours alternatif",
    category: "React",
    desc: "Un cours bien construit (en anglais) avec de l'interactivité pour appliquer les concepts",
  },
  {
    name: "Re-size pixel",
    link: "https://www.resizepixel.com/fr/resize-image/",
    type: "Images et Vidéos",
    category: "CSS",
    desc: "pour redimensionner des photos et réduire la qualité",
  },
  {
    name: "Exercism",
    link: "https://exercism.org",
    type: "Pratique / Exercices",
    category: "JS",
    desc: "Des challenge JS avec une progression en difficulté, accès a des mentor pour review votre code gratuitement",
  },
  {
    name: "CodeWars",
    link: "https://codewars.com",
    type: "Pratique / Exercices",
    category: "JS",
    desc: "Plus de katas JS ",
  },
  {
    name: "Condingame",
    link: "https://www.codingame.com",
    type: "Pratique / Exercices",
    category: "JS",
    desc: "Plateforme de jeux algorithmiques aussi utilisée pour les tests techniques en entreprise",
  },
  {
    name: "Grafikart",
    link: "https://grafikart.fr/tutoriels",
    type: "Cours alternatif",
    category: "JS",
    desc: "énormement de cours vidéo différents",
  },
  {
    name: "Caniuse",
    link: "https://caniuse.com/",
    type: "Autres",
    category: "Autre",
    desc: "pour savoir si une fonctionnalité est gérée par les navigateurs",
  },
  {
    name: "Pexels",
    link: "https://www.pexels.com/fr-fr/",
    type: "Images et Vidéos",
    category: "UX/UI",
    desc: "images libre de droit/ banque d'images et photos gratuite",
  },
  {
    name: "Freepik",
    link: "https://fr.freepik.com/",
    type: "Images et Vidéos",
    category: "UX/UI",
    desc: "images libre de droit/ images vectorielles, psd et photos",
  },
  {
    name: "Unsplash",
    link: "https://unsplash.com/fr",
    type: "Images et Vidéos",
    category: "UX/UI",
    desc: "images libre de droit",
  },
  {
    name: "Logo ipsum",
    link: "https://logoipsum.com/",
    type: "Conception UI",
    category: "UI / UX",
    desc: "faire un mockup de logo",
  },
  {
    name: "React",
    link: "https://react.gg/ ",
    type: "Resource interactive",
    category: "React",
    desc: "Un site interactif qui présente brièvement React, d'une manière intéressante",
  },
  {
    name: "Github storybook JS",
    link: "https://github.com/storybookjs/storybook",
    type: "Outil de dev",
    category: "React",
    desc: "Un outil pour créer votre propre bibliothèque de composants de manière à pouvoir les réutiliser d'un projet à l'autre",
  },
  {
    name: "Wattenberger",
    link: "https://wattenberger.com/blog/react-hooks",
    type: "Article",
    category: "React",
    desc: "Un article intéressant sur les Hooks React, qui compare l'utilisation en mode traditionel (dans une classe) et avec les composants fonctionels.",
  },
  {
    name: "Tympanus",
    link: "https://tympanus.net/codrops/",
    type: "Resource interactive",
    category: "CSS",
    desc: "Examples d'animations avancées CSS/JS, avec explications, lien vers les dépots Gits etc...",
  },
  {
    name: "Anthony gorski promesses et async/await",
    link: "https://anthony-gorski.notion.site/Asynchrone-9c3cc619bd4c42559019f927b7d3fe3f",
    type: "Article",
    category: "JS",
    desc: "Article d'un autre enseignant de la Wild sur le thème des promesses (objet Promise) et async/await",
  },
  {
    name: " En.rakko",
    link: "https://en.rakko.tools/tools/9/",
    type: "Outil de dev",
    category: "UI/UX",
    desc: "Permet de tester comment seraient affichées les métadonnées opengraph d'une URL donnée",
  },
  {
    name: "Opengraph",
    link: "https://www.opengraph.io/",
    type: "API",
    category: "UI/UX",
    desc: "API pour obtenir les métadonnées opengraph d'une URL donnée",
  },
  {
    name: "embed.rocks",
    link: "https://embed.rocks/docs",
    type: "API",
    category: "JS",
    desc: "API pour obtenir les métadonnées opengraph d'une URL donnée",
  },
  {
    name: "React icons",
    link: "https://react-icons.github.io/react-icons/ ",
    type: "Images et Vidéos",
    category: "React",
    desc: "De quoi inclure des incones dans vos applis React",
  },
  {
    name: "Futurpedia",
    link: "https://www.futurepedia.io/",
    type: "Site Répertoire",
    category: "Autre",
    desc: "Un site qui repertorie plein d'outils IA plus ou moins utiles, gratuites ou payantes ",
  },
  {
    name: "The Odin Project",
    link: "https://www.theodinproject.com/",
    type: "Cours alternatif",
    category: "Autre",
    desc: "Un  cours qui reprend tout ce que lon a vu et fait: avec des nouvelles quests pour par refaire les memes",
  },
  {
    name: "Dailydev",
    link: "https://app.daily.dev/popular",
    type: "Veille techno",
    category: "Veille techno",
    desc: "site d'infos sur le code et la tech, veille technologique en anglais",
  },
  {
    name: "Ardèche Drome Dev",
    link: "https://www.ardechdromdev.org/",
    type: "asso",
    category: "Autre",
    desc: "Association de développeurs Valence et alentour",
  },
  {
    name: "HTML / CSS / JS",
    link: "https://html-css-js.com/html/",
    type: "Support",
    category: "HTML",
    desc: "Generator de code html / cheat sheet / editor",
  },
  {
    name: " FlexBox Guide",
    link: "https://www.joshwcomeau.com/css/interactive-guide-to-flexbox/",
    type: "cours",
    category: "CSS",
    desc: "An interactive guide to flexbox",
  },
  {
    name: "MDN mozilla developer",
    link: "https://developer.mozilla.org/en-US/",
    type: "cours",
    category: "JS",
    desc: "Bible Javascript",
  },
  {
    name: "La cascade",
    link: "https://la-cascade.io/articles/flexbox-guide-complet",
    type: "cours",
    category: "CSS",
    desc: "Guide flexbox complet en français",
  },
  {
    name: "stackblitz",
    link: "https://stackblitz.com/fork/web-platform",
    type: "editeur",
    category: "Autre",
    desc: "Editeur de code en ligne",
  },
  {
    name: "codepen",
    link: "https://codepen.io/",
    type: "editeur",
    category: "Autre",
    desc: "Editeur de code en ligne",
  },
  {
    name: "codesandbox",
    link: "https://codesandbox.io/dashboard/recent",
    type: "editeur",
    category: "Autre",
    desc: "Editeur de code en ligne",
  },
  {
    name: "replit",
    link: "https://replit.com/~",
    type: "editeur",
    category: "Autre",
    desc: "Editeur de code en ligne",
  },
  {
    name: "Codewars",
    link: "https://www.codewars.com",
    type: "algo",
    category: "Algo",
    desc: "Plateform de jeux algorithmique",
  },
  {
    name: "Codingame",
    link: "https://www.codingame.com/home",
    type: "algo",
    category: "Algo",
    desc: "Plateform de jeux algorithmique",
  },
  {
    name: "Blocky Games",
    link: "https://blockly.games/",
    type: "algo",
    category: "Algo",
    desc: "Plateform de jeux algorithmique",
  },
  {
    name: "User Inyerface",
    link: "https://userinyerface.com/",
    type: "UX/UI",
    category: "UX/UI",
    desc: "Le pire exemple d'UX/UI design",
  },
  {
    name: "Indeed",
    link: "https://fr.indeed.com/",
    type: "recherche",
    category: "Emploi",
    desc: "Site de recherche d'emploi dédié au monde de la tech ",
  },
  {
    name: "Hello Work",
    link: "https://www.hellowork.com/fr-fr/",
    type: "recherche",
    category: "Emploi",
    desc: "Site de recherche d'emploi dédié au monde de la tech ",
  },
  {
    name: "Linkedin",
    link: "https://www.linkedin.com/jobs/?originalSubdomain=fr",
    type: "recherche",
    category: "Emploi",
    desc: "Site de recherche d'emploi dédié au monde de la tech ",
  },
  {
    name: "Welcome to the jungle",
    link: "https://www.welcometothejungle.com/fr",
    type: "recherche",
    category: "Emploi",
    desc: "Site de recherche d'emploi dédié au monde de la tech ",
  },
  {
    name: "Externatic",
    link: "https://www.externatic.fr/",
    type: "recherche",
    category: "Emploi",
    desc: "Site de recherche d'emploi dédié au monde de la tech ",
  },
  {
    name: "Solers.io",
    link: "https://www.solers.io/",
    type: "recherche",
    category: "Emploi",
    desc: "Site de recherche d'emploi dédié au monde de la tech ",
  },
  {
    name: "Bao",
    link: "https://bao.jobs/",
    type: "recherche",
    category: "Emploi",
    desc: "Site de recherche d'emploi dédié au monde de la tech ",
  },
  {
    name: "Monster",
    link: "https://www.monster.fr/",
    type: "recherche",
    category: "Emploi",
    desc: "Site de recherche d'emploi dédié au monde de la tech ",
  },
  {
    name: "Meteo Job",
    link: "https://www.meteojob.com/",
    type: "recherche",
    category: "Emploi",
    desc: "Site de recherche d'emploi dédié au monde de la tech ",
  },
  {
    name: "Les jeudis.com",
    link: "https://lesjeudis.com/",
    type: "recherche",
    category: "Emploi",
    desc: "Site de recherche d'emploi dédié au monde de la tech ",
  },
  {
    name: "Emploi AFJV",
    link: "https://emploi.afjv.com/",
    type: "recherche",
    category: "Emploi",
    desc: "Site de recherche d'emploi dédié au monde de la tech ",
  },
  {
    name: "Digitaweb",
    link: "https://www.digitaweb.com/blog/liste-job-board-fran%C3%A7ais",
    type: "recherche",
    category: "Emploi",
    desc: "Site de recherche d'emploi dédié au monde de la tech ",
  },

  {
    name: "Coolors",
    link: "https://coolors.co/",
    type: "ux/ui",
    category: "UX/UI",
    desc: "Generateur de palettes de couleures",
  },
  {
    name: "Coolors picker",
    link: "https://coolors.co/image-picker",
    type: "ux/ui",
    category: "UX/UI",
    desc: "Récuperer les code couleurs d'une photo",
  },
  {
    name: "Canva color palettes",
    link: "https://www.canva.com/colors/color-palettes/",
    type: "ux/ui",
    category: "UX/UI",
    desc: "Generateur de palettes de couleures",
  },
  {
    name: "Frontend Roadmap",
    link: "https://roadmap.sh/frontend",
    type: "roadmap",
    category: "Autre",
    desc: "Roadmap développeur frontend ",
  },
  {
    name: "Render",
    link: "https://render.com/",
    type: "deploy",
    category: "React",
    desc: "Hebergeur pour deploiement ",
  },
  {
    name: "Netlify",
    link: "https://www.netlify.com/",
    type: "deploy",
    category: "React",
    desc: "Hebergeur pour deploiement ",
  },
  {
    name: "Vercel",
    link: "https://vercel.com/",
    type: "deploy",
    category: "React",
    desc: "Hebergeur pour deploiement ",
  },
  {
    name: "Github Pages",
    link: "https://www.npmjs.com/package/gh-pages",
    type: "deploy",
    category: "React",
    desc: "Hebergeur pour deploiement ",
  },
  {
    name: "Clever cloud",
    link: "https://www.clever-cloud.com/fr/",
    type: "deploy",
    category: "React",
    desc: "Hebergeur pour deploiement de base de données ",
  },
  {
    name: "Cap rover",
    link: "https://caprover.com/",
    type: "deploy",
    category: "React",
    desc: "Hebergeur pour deploiement ",
  },
  {
    name: "Doc React",
    link: "https://react.dev/",
    type: "doc",
    category: "React",
    desc: "Documentation React",
  },
  {
    name: "Embed Rocks",
    link: "https://embed.rocks/",
    type: "api",
    category: "Autre",
    desc: "API de récuperation des données opengraph",
  },
  {
    name: "SQL island",
    link: "https://sql-island.informatik.uni-kl.de/",
    type: "sql",
    category: "Autre",
    desc: "Jeu SQL",
  },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
  //   { name: "", link: "", type: "", category: "", desc: "" },
];

const tools = [
  {
    name: "Odyssey",
    link: "https://odyssey.wildcodeschool.com/",
    img: logoWild,
  },
  {
    name: "Slack",
    link: "https://app.slack.com/client/T6SG2QGG2/C04QMQPS0MA/thread/C04QMQPS0MA-1682777525.981379",
    img: logoSlack,
  },
  {
    name: "Google meet",
    link: "https://meet.google.com/qki-zcjy-wsf?pli=1",
    img: logoMeet,
  },
  { name: "Github", link: "https://github.com/", img: logoGithub },
  {
    name: "Google Drive",
    link: "https://drive.google.com/drive/folders/14tXIpvlHcrW_U5f_yyGYSQ6EGb2s47D3",
    img: logoDrive,
  },
  { name: "Figma", link: "https://www.figma.com/fr/", img: logoFigma },
  { name: "Trello", link: "https://trello.com/fr", img: logoTrello },
  {
    name: "Discord",
    link: "https://discord.com/channels/1085967285283467345/1085967285283467350",
    img: logoDiscord,
  },
];

export default student;
export { tools, links };
